pagy:
  instances:
    vars: vars
  items_default: 30
  page_default: 1
jwt:
  expiration_time: 18000
  algorithm: HS256
  token_type: Bearer
sendgrid:
  success_code: ["200", "202", "204"]
  batch_size: 100
sidekiq:
  mailers:
    retry: 5
  consumer:
    retry: 3
epoch_time:
  day_in_secs: 86400
user:
  password:
    regexp: !ruby/regexp /\A(?=.*[a-z])(?=.*[A-Z])(?=.*\d)(?=.*[@$!%*#?&])[a-zA-Z\d@$!%*#?&]{8,}\z/
    minimum: 8
